name: Install
inputs:
  fromArtifact:
    default: 'false'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        if [[ "${{ inputs.fromArtifact }}" == "false" ]]; then
          sudo make install
        fi
        sudo mkdir -p /etc/php.d
        sudo chmod 777 /etc/php.d
